apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafdrop
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/obsidiandynamics/kafdrop.git
    targetRevision: HEAD
    path: chart
    helm:
      releaseName: kafdrop
      values: |
        global: 
          security:
            allowInsecureImages: true

        image:
          repository: obsidiandynamics/kafdrop
          tag: "4.0.2"
          pullPolicy: IfNotPresent

        kafka:
          brokerConnect: "kafka-broker-0.kafka-broker-headless.default.svc.cluster.local:9094"
          # properties: |
          #   security.protocol=SASL_SSL
          #   sasl.mechanism=PLAIN
          #   sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="user" password="pass";

        server:
          servlet:
            contextPath: "/"

        jvm:
          opts: "-Xms128M -Xmx256M"

        service:
          type: NodePort
          port: 9000
          nodePort: 32090

        ingress:
          enabled: false
          className: ""
          hosts:
            - host: "kafdrop.example.com"
              paths:
                - path: /
                  pathType: Prefix
          tls: []

        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: tools
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
