apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: health-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/aleksey6689/sandbox_files.git'
    targetRevision: main
    path: deployments/health-server
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true